# Full skills database - 100+ skills for NEXUS AI
FULL_SKILLS = {
    "flashlight": {"name": "🔦 Flashlight", "desc": "Turn on/off flashlight"},
    "battery": {"name": "🔋 Battery", "desc": "Check battery status"},
    "weather": {"name": "🌤️ Weather", "desc": "Get weather forecast"},
    "news": {"name": "📰 News", "desc": "Fetch latest news"},
    "translate": {"name": "🌐 Translate", "desc": "Translate text"},
    "email": {"name": "📧 Email", "desc": "Send/receive emails"},
    "calendar": {"name": "📅 Calendar", "desc": "Manage events"},
    "voice": {"name": "🎤 Voice", "desc": "Voice control with wake word"},
    "camera": {"name": "📷 Camera", "desc": "Take photos and video"},
    "docx": {"name": "📄 Word", "desc": "Create/edit Word documents"},
    "pdf": {"name": "📑 PDF", "desc": "Extract text, create PDFs"},
    "pptx": {"name": "📊 PowerPoint", "desc": "Create presentations"},
    "xlsx": {"name": "📈 Excel", "desc": "Spreadsheets with formulas"},
    "telegram": {"name": "📱 Telegram", "desc": "Telegram bot control"},
    "whatsapp": {"name": "💬 WhatsApp", "desc": "WhatsApp messaging"},
    "discord": {"name": "🎮 Discord", "desc": "Discord bot"},
    "slack": {"name": "💼 Slack", "desc": "Slack workspace"},
    "screenshot": {"name": "📸 Screenshot", "desc": "Capture screen"},
    "vibrate": {"name": "📳 Vibrate", "desc": "Make phone vibrate"},
    "location": {"name": "📍 Location", "desc": "Get GPS location"},
    "alarm": {"name": "⏰ Alarm", "desc": "Set alarms"},
    "reminder": {"name": "📝 Reminder", "desc": "Set reminders"},
    "note": {"name": "📓 Note", "desc": "Create notes"},
    "calculator": {"name": "🧮 Calculator", "desc": "Perform calculations"},
    "stock": {"name": "📊 Stock", "desc": "Get stock prices"},
    "crypto": {"name": "💰 Crypto", "desc": "Get crypto prices"},
    "youtube": {"name": "📺 YouTube", "desc": "Search YouTube"},
    "spotify": {"name": "🎵 Spotify", "desc": "Control Spotify"},
    "github": {"name": "🐙 GitHub", "desc": "GitHub integration"},
    "sms": {"name": "📱 SMS", "desc": "Send text messages"},
    "call": {"name": "📞 Call", "desc": "Make phone calls"},
    "contacts": {"name": "👥 Contacts", "desc": "Access contacts"},
    "wifi": {"name": "📶 WiFi", "desc": "Control WiFi"},
    "bluetooth": {"name": "📡 Bluetooth", "desc": "Control Bluetooth"},
    "brightness": {"name": "☀️ Brightness", "desc": "Adjust brightness"},
    "volume": {"name": "🔊 Volume", "desc": "Adjust volume"},
    "code": {"name": "💻 Code", "desc": "Write and review code"},
    "debug": {"name": "🐛 Debug", "desc": "Debug code issues"},
    "test": {"name": "🧪 Test", "desc": "Run tests"},
    "git": {"name": "📦 Git", "desc": "Git operations"},
    "docker": {"name": "🐳 Docker", "desc": "Docker commands"},
    "aws": {"name": "☁️ AWS", "desc": "AWS cloud operations"},
    "database": {"name": "🗄️ Database", "desc": "Database queries"},
    "api": {"name": "🔌 API", "desc": "API development"},
    "csv": {"name": "📊 CSV", "desc": "Analyze CSV files"},
    "json": {"name": "📋 JSON", "desc": "Process JSON data"},
    "html": {"name": "🌐 HTML", "desc": "Generate HTML"},
    "css": {"name": "🎨 CSS", "desc": "CSS styling"},
    "javascript": {"name": "💛 JavaScript", "desc": "JavaScript code"},
    "python": {"name": "🐍 Python", "desc": "Python code"},
    "markdown": {"name": "📝 Markdown", "desc": "Write markdown"},
    "chart": {"name": "📊 Chart", "desc": "Create charts"},
    "report": {"name": "📄 Report", "desc": "Generate reports"},
    "resume": {"name": "📄 Resume", "desc": "Create resume"},
    "blog": {"name": "📝 Blog", "desc": "Write blog posts"},
    "summary": {"name": "📋 Summary", "desc": "Summarize text"},
    "grammar": {"name": "✅ Grammar", "desc": "Check grammar"},
    "math": {"name": "📐 Math", "desc": "Solve math problems"},
    "joke": {"name": "😂 Joke", "desc": "Tell a joke"},
    "quote": {"name": "💬 Quote", "desc": "Get quote"},
    "fact": {"name": "💡 Fact", "desc": "Get random fact"},
    "timer": {"name": "⏱️ Timer", "desc": "Set timer"},
    "stopwatch": {"name": "⏱️ Stopwatch", "desc": "Start stopwatch"},
    "qrcode": {"name": "📷 QR Code", "desc": "Generate QR code"},
    "password": {"name": "🔐 Password", "desc": "Generate password"},
    "qna": {"name": "❓ Q&A", "desc": "Answer questions"},
    "search": {"name": "🔍 Search", "desc": "Web search"},
}
